print("Olá turma do Python!")
print("Como Esta?")
nome: str = input("Qual é o seu nome? ")
print(f"Olá, {nome}!")
idade: int = int(input("Qual é a sua idade? "))
print(f"Tu tens {idade} anos...")
zona: str = input("De onde es? ")
print(f"Es de {zona}")
print("Obrigado")
print("Ate a proxima!!")